[package]
name = "asteroids"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.8"

[dev-dependencies]
axum = { version = "0.7.5", features = ["macros"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["fs"]}
